[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "(cd client && npm ci) || true",
  "(cd server && npm ci) || true"
]

[phases.build]
cmds = [
  "test -d client && cd client && npm run build || echo 'Client directory not found, skipping build'"
]

[start]
cmd = "cd server && node index.js"
